### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException:

### ISSUE THREAD

**Issue by qwazer** [qwazer/maven-confluence-plugin#12]
[INFO] Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
[INFO]  at java.util.ArrayList.elementData(ArrayList.java:371)
[INFO]  at java.util.ArrayList.get(ArrayList.java:384)
[INFO]  at com.github.qwazer.mavenplugins.gitlog.VersionUtil.findNearestVersionTagsBefore(VersionUtil.java:136)
[INFO]  at org.bsc.maven.reporting.renderer.GitLogJiraIssuesRenderer.overrideGitLogSinceTagNameIfNeeded(GitLogJiraIssuesRenderer.java:173)
[INFO]  at org.bsc.maven.reporting.renderer.GitLogJiraIssuesRenderer.renderBody(GitLogJiraIssuesRenderer.java:104)
[INFO]  at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:79)
[INFO]  at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.generateProjectReport(ConfluenceDeployMojo.java:382)
[INFO]  at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.execute(ConfluenceDeployMojo.java:243)
[INFO]  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
[INFO]  ... 20 more

**Comment by qwazer** [comment]
```
Index: maven-confluence-reporting-plugin/src/main/java/com/github/qwazer/mavenplugins/gitlog/VersionUtil.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>windows-1251
===================================================================
--- maven-confluence-reporting-plugin/src/main/java/com/github/qwazer/mavenplugins/gitlog/VersionUtil.java  (date 1431517010000)
+++ maven-confluence-reporting-plugin/src/main/java/com/github/qwazer/mavenplugins/gitlog/VersionUtil.java  (date 1431603218000)
@@ -133,7 +133,12 @@
             return map.get(sortedList.get(index));
         }
         if (sortedList.size() > 0) {
+            if (-index-2>=0) {
-            return map.get(sortedList.get(-index - 2));
+                return map.get(sortedList.get(-index - 2));
+            }
+            else {
+                return null;
+            }
         } else {
             return null;
         }
```
